### ISSUE TITLE
Make sure ARIA live regions are shared between instances of the module.

### ISSUE THREAD

**Issue by omarreiss** [Yoast/a11y-speak#7]
We should decide if we want to add separate ARIA live regions for every instance of the module or if the different instances of the module can share their regions.

If we don't share the regions, they should have unique id's.

If we do share the region, we should check if they were already appended to the page before adding them.

**Comment by omarreiss** [comment]
@afercia can you think of a reason why we should have multiple ARIA live regions?

**Comment by afercia** [comment]
@omarreiss I think different instances should share the aria-live regions, there's no reason to have multiple ones because screen readers can't read out multiple messages simultaneously. Wouldn't [the existing checks](https://github.com/Yoast/a11y-speak/pull/5/files#diff-ef4ea9b92f3f28666dcf3b839d1d85e5R45) be enough?

**Comment by omarreiss** [comment]
If different javascripts require the same module, they will create multiple regions. This can be prevented by checking if the regions are already present on the page, instead of doing a null check. I'll PR tomorrow.
